apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1m5j
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-1m5j@sha256:e0f19692a66ac51b95441287753faa6f17b817b35c3b55beef5d21f16a8e06d8
        name: my-nodejs
        resources: {}
status: {}
